spring:
  datasource:
    url: 'jdbc:h2:mem:pokedex'
    username: 'sa'
    password: 'password'
    driverClassName: 'org.h2.Driver'
  h2:
    console:
      enabled: true
      path: "/console/"
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  devtools:
    restart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: "app/log/${POD_NAME:monitoring}.log"
  level:
    org:
      hibernate: DEBUG

#flyway:
#  user: 'root'
#  password: '12345678@'
#  schemas: 'pokedex'
#  url: 'jdbc:mysql://localhost:3306/pokedex'V1__initialV1__initial