spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/pokedex'
    username: 'root'
    password: '12345678@'
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  devtools:
    restart:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#flyway:
#  user: 'root'
#  password: '12345678@'
#  schemas: 'pokedex'
#  url: 'jdbc:mysql://localhost:3306/pokedex'V1__initialV1__initial