apiVersion: v1
kind: ConfigMap
metadata:
  name: pokebattle-config
  namespace: pokebattle
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://pokebattle-db.database.svc.cluster.local:3306/pokedex
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: 123455678@