apiVersion: v1
kind: Namespace
metadata:
  name: pokebattle

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-be
  namespace: pokebattle
  labels:
    app: pokedex-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex-be
  template:
    metadata:
      labels:
        app: pokedex-be
    spec:
      containers:
        - name: pokedex-be
          image: docker.io/lukas8219/pokebattle
          envFrom:
            - configMapRef:
                name: pokebattle-config
          ports:
           - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pokedex-be
  namespace: pokebattle
  labels:
    app: pokedex-be
spec:
  type: NodePort
  ports:
    - port : 8080
      targetPort: 8080
  selector:
    app: pokedex-be