apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: pokebattle
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pokedex-be
                port:
                  number: 8080