apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data
  namespace: pokebattle
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-data
  namespace: pokebattle
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/logs/"