
INSERT INTO POKEMON_TYPES VALUES (1,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (1,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (2,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (2,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (3,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (3,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (4,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (5,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (6,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (6,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (7,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (8,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (9,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (10,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (11,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (12,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (12,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (13,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (13,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (14,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (14,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (15,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (15,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (16,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (16,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (17,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (17,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (18,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (18,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (19,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (20,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (21,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (21,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (22,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (22,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (23,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (24,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (25,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (26,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (27,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (28,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (29,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (30,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (31,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (31,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (32,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (33,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (34,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (34,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (35,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (36,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (37,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (38,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (39,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (39,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (40,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (40,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (41,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (41,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (42,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (42,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (43,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (43,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (44,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (44,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (45,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (45,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (46,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (46,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (47,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (47,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (48,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (48,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (49,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (49,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (50,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (51,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (52,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (53,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (54,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (55,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (56,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (57,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (58,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (59,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (60,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (61,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (62,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (62,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (63,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (64,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (65,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (66,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (67,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (68,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (69,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (69,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (70,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (70,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (71,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (71,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (72,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (72,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (73,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (73,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (74,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (74,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (75,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (75,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (76,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (76,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (77,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (78,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (79,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (79,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (80,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (80,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (81,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (81,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (82,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (82,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (83,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (83,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (84,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (84,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (85,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (85,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (86,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (87,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (87,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (88,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (89,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (90,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (91,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (91,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (92,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (92,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (93,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (93,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (94,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (94,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (95,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (95,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (96,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (97,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (98,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (99,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (100,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (101,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (102,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (102,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (103,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (103,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (104,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (105,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (106,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (107,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (108,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (109,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (110,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (111,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (111,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (112,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (112,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (113,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (114,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (115,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (116,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (117,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (118,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (119,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (120,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (121,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (121,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (122,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (122,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (123,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (123,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (124,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (124,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (125,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (126,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (127,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (128,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (129,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (130,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (130,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (131,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (131,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (132,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (133,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (134,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (135,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (136,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (137,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (138,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (138,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (139,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (139,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (140,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (140,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (141,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (141,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (142,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (142,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (143,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (144,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (144,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (145,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (145,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (146,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (146,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (147,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (148,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (149,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (149,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (150,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (151,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (152,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (153,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (154,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (155,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (156,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (157,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (158,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (159,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (160,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (161,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (162,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (163,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (163,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (164,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (164,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (165,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (165,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (166,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (166,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (167,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (167,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (168,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (168,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (169,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (169,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (170,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (170,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (171,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (171,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (172,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (173,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (174,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (174,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (175,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (176,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (176,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (177,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (177,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (178,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (178,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (179,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (180,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (181,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (182,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (183,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (183,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (184,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (184,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (185,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (186,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (187,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (187,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (188,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (188,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (189,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (189,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (190,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (191,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (192,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (193,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (193,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (194,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (194,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (195,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (195,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (196,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (197,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (198,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (198,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (199,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (199,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (200,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (201,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (202,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (203,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (203,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (204,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (205,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (205,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (206,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (207,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (207,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (208,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (208,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (209,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (210,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (211,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (211,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (212,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (212,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (213,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (213,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (214,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (214,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (215,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (215,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (216,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (217,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (218,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (219,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (219,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (220,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (220,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (221,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (221,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (222,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (222,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (223,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (224,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (225,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (225,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (226,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (226,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (227,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (227,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (228,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (228,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (229,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (229,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (230,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (230,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (231,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (232,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (233,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (234,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (235,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (236,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (237,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (238,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (238,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (239,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (240,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (241,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (242,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (243,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (244,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (245,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (246,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (246,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (247,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (247,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (248,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (248,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (249,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (249,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (250,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (250,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (251,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (251,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (252,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (253,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (254,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (255,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (256,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (256,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (257,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (257,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (258,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (259,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (259,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (260,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (260,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (261,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (262,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (263,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (264,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (265,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (266,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (267,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (267,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (268,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (269,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (269,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (270,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (270,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (271,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (271,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (272,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (272,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (273,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (274,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (274,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (275,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (275,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (276,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (276,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (277,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (277,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (278,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (278,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (279,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (279,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (280,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (280,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (281,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (281,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (282,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (282,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (283,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (283,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (284,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (284,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (285,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (286,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (286,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (287,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (288,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (289,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (290,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (290,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (291,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (291,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (292,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (292,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (293,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (294,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (295,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (296,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (297,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (298,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (298,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (299,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (300,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (301,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (302,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (302,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (303,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (303,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (304,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (304,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (305,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (305,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (306,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (306,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (307,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (307,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (308,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (308,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (309,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (310,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (311,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (312,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (313,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (314,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (315,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (315,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (316,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (317,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (318,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (318,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (319,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (319,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (320,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (321,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (322,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (322,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (323,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (323,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (324,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (325,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (326,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (327,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (328,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (329,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (329,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (330,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (330,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (331,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (332,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (332,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (333,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (333,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (334,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (334,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (335,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (336,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (337,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (337,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (338,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (338,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (339,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (339,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (340,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (340,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (341,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (342,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (342,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (343,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (343,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (344,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (344,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (345,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (345,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (346,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (346,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (347,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (347,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (348,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (348,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (349,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (350,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (351,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (352,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (353,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (354,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (355,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (356,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (357,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (357,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (358,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (359,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (360,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (361,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (362,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (363,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (363,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (364,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (364,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (365,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (365,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (366,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (367,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (368,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (369,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (369,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (370,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (371,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (372,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (373,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (373,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (374,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (374,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (375,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (375,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (376,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (376,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (377,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (378,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (379,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (380,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (380,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (381,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (381,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (382,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (383,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (384,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (384,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (385,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (385,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (386,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (387,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (388,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (389,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (389,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (390,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (391,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (391,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (392,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (392,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (393,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (394,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (395,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (395,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (396,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (396,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (397,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (397,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (398,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (398,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (399,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (400,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (400,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (401,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (402,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (403,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (404,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (405,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (406,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (406,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (407,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (407,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (408,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (409,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (410,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (410,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (411,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (411,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (412,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (413,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (413,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (414,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (414,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (415,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (415,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (416,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (416,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (417,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (418,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (419,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (420,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (421,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (422,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (423,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (423,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (424,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (425,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (425,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (426,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (426,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (427,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (428,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (429,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (430,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (430,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (431,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (432,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (433,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (434,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (434,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (435,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (435,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (436,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (436,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (437,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (437,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (438,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (439,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (439,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (440,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (441,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (441,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (442,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (442,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (443,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (443,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (444,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (444,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (445,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (445,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (446,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (447,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (448,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (448,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (449,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (450,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (451,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (451,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (452,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (452,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (453,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (453,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (454,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (454,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (455,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (456,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (457,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (458,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (458,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (459,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (459,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (460,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (460,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (461,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (461,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (462,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (462,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (463,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (464,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (464,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (465,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (466,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (467,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (468,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (468,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (469,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (469,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (470,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (471,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (472,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (472,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (473,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (473,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (474,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (475,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (475,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (476,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (476,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (477,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (478,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (478,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (479,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (479,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (480,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (481,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (482,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (483,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (483,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (484,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (484,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (485,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (485,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (486,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (487,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (487,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (488,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (489,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (490,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (491,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (492,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (493,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (494,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (494,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (495,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (496,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (497,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (498,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (499,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (499,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (500,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (500,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (501,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (502,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (503,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (504,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (505,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (506,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (507,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (508,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (509,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (510,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (511,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (512,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (513,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (514,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (515,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (516,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (517,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (518,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (519,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (519,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (520,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (520,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (521,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (521,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (522,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (523,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (524,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (525,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (526,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (527,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (527,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (528,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (528,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (529,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (530,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (530,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (531,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (532,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (533,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (534,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (535,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (536,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (536,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (537,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (537,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (538,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (539,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (540,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (540,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (541,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (541,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (542,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (542,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (543,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (543,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (544,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (544,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (545,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (545,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (546,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (546,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (547,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (547,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (548,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (549,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (550,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (551,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (551,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (552,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (552,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (553,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (553,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (554,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (555,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (556,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (557,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (557,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (558,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (558,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (559,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (559,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (560,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (560,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (561,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (561,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (562,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (563,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (564,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (564,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (565,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (565,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (566,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (566,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (567,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (567,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (568,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (569,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (570,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (571,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (572,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (573,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (574,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (575,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (576,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (577,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (578,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (579,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (580,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (580,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (581,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (581,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (582,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (583,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (584,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (585,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (585,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (586,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (586,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (587,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (587,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (588,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (589,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (589,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (590,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (590,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (591,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (591,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (592,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (592,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (593,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (593,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (594,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (595,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (595,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (596,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (596,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (597,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (597,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (598,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (598,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (599,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (600,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (601,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (602,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (603,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (604,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (605,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (606,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (607,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (607,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (608,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (608,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (609,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (609,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (610,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (611,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (612,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (613,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (614,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (615,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (616,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (617,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (618,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (618,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (619,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (620,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (621,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (622,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (622,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (623,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (623,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (624,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (624,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (625,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (625,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (626,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (627,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (627,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (628,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (628,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (629,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (629,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (630,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (630,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (631,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (632,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (632,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (633,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (633,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (634,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (634,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (635,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (635,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (636,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (636,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (637,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (637,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (638,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (638,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (639,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (639,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (640,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (640,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (641,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (642,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (642,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (643,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (643,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (644,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (644,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (645,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (645,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (646,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (646,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (647,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (647,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (648,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (648,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (649,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (649,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (650,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (651,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (652,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (652,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (653,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (654,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (655,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (655,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (656,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (657,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (658,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (658,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (659,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (660,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (660,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (661,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (661,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (662,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (662,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (663,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (663,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (664,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (665,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (666,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (666,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (667,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (667,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (668,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (668,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (669,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (670,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (671,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (672,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (673,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (674,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (675,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (675,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (676,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (677,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (678,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (679,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (679,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (680,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (680,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (681,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (681,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (682,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (683,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (684,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (685,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (686,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (686,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (687,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (687,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (688,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (688,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (689,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (689,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (690,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (690,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (691,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (691,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (692,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (693,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (694,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (694,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (695,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (695,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (696,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (696,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (697,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (697,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (698,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (698,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (699,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (699,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (700,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (701,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (701,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (702,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (702,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (703,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (703,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (704,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (705,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (706,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (707,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (707,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (708,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (708,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (709,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (709,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (710,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (710,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (711,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (711,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (712,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (713,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (714,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (714,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (715,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (715,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (716,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (717,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (717,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (718,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (718,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (719,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (719,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (720,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (720,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (721,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (721,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (722,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (722,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (723,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (723,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (724,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (724,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (725,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (726,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (727,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (727,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (728,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (729,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (730,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (730,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (731,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (731,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (732,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (732,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (733,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (733,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (734,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (735,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (736,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (737,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (737,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (738,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (738,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (739,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (740,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (740,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (741,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (741,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (742,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (742,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (743,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (743,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (744,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (745,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (746,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (747,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (747,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (748,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (748,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (749,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (750,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (751,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (751,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (752,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (752,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (753,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (754,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (755,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (755,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (756,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (756,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (757,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (757,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (758,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (758,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (759,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (759,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (760,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (760,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (761,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (762,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (763,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (764,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (765,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (765,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (766,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (767,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (767,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (768,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (768,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (769,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (769,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (770,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (770,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (771,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (772,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (773,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (774,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (774,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (775,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (776,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (776,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (777,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (777,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (778,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (778,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (779,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (779,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (780,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (780,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (781,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (781,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (782,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (783,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (783,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (784,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (784,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (785,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (785,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (786,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (786,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (787,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (787,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (788,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (788,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (789,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (790,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (791,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (791,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (792,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (792,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (793,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (793,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (794,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (794,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (795,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (795,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (796,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (797,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (797,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (798,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (798,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (799,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (799,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (800,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (801,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (801,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (802,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (802,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (803,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (804,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (804,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (805,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (805,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (806,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (806,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (807,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (808,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (809,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (810,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (811,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (812,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (813,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (814,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (815,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (816,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (817,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (818,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (819,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (820,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (821,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (822,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (823,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (823,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (824,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (825,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (825,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (826,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (826,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (827,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (828,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (829,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (830,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (831,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (832,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (833,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (834,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (834,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (835,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (836,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (837,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (838,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (838,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (839,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (839,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (840,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (840,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (841,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (841,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (842,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (842,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (843,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (844,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (845,'FLYING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (845,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (846,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (847,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (848,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (848,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (849,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (849,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (850,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (850,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (851,'FIRE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (851,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (852,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (853,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (854,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (855,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (856,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (857,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (858,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (858,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (859,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (859,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (860,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (860,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (861,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (861,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (862,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (862,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (863,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (864,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (865,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (866,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (866,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (867,'GROUND');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (867,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (868,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (869,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (870,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (871,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (872,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (872,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (873,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (873,'BUG');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (874,'ROCK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (875,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (876,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (876,'NORMAL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (877,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (877,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (878,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (879,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (880,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (880,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (881,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (881,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (882,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (882,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (883,'WATER');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (883,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (884,'STEEL');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (884,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (885,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (885,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (886,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (886,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (887,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (887,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (888,'FAIRY');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (889,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (890,'POISON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (890,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (891,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (892,'FIGHTING');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (892,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (893,'DARK');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (893,'GRASS');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (894,'ELECTRIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (895,'DRAGON');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (896,'ICE');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (897,'GHOST');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (898,'PSYCHIC');

INSERT INTO POKEMON_TYPES(pokemon_id, type) VALUES (898,'GRASS');
COMMIT;
