name: 'Publish'
on:
  push:
    branches:
      - master
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Code
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Java Image
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_pass: ${{ secrets.DOCKERHUB_TOKEN }}
        run: ./gradlew build jib -x test