name: Linter
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#      - name: Lint Code Base
#        uses: github/super-linter@v4
#        env:
#          VALIDATE_ALL_CODEBASE: false
#          DEFAULT_BRANCH: master
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Login into Dockerhub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Push Image to DockerHub
#        uses: docker/build-push-action@v2

        - name: Generate Tag
          id: generate_tag
          uses: Surgo/docker-smart-tag-action@v1
          with:
            docker_image: name/app
            tag_with_sha: true

          run: echo ${{ steps.generate_tag.outputs.tag }}
