name: Linter
on:
  pull_request:
    branches:
      - master
jobs:
  Checkout:
    runs-on: ubuntu-latest
    env:
      - REPO: ${{ secrets.DOCKERHUB_REPO }}
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login into Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_TOKEN_ID}

      - name: Push Docker Imagem
        run: docker push $REPO

