name: Linter
on:
  pull_request:
    branches:
      - master
jobs:
  Checkout:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.event.repository.name }}
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login into Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Tag
        id: generate_tag
        uses: Surgo/docker-smart-tag-action@v1
        with:
          docker_image: $REPO
          default_branch: ${{ github.event.repository.default_branch }}
          tag_with_sha: true

      - name: Build Docker Image
        run: docker build -t lukas8219/${{ steps.generate_tag.outputs.tag }} -t lukas8219/${{ steps.generate_tag.outputs.tag }}

      - name: Push Docker Imagem
        run: docker push lukas8219/${{ steps.generate_tag.outputs.tag }}

