name: Linter
on:
  push:
    branches:
      - master
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login into Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Java Image
        env:
          docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_pass: ${{ secrets.DOCKERHUB_TOKEN }}
        run: ./gradlew build jib -x test

      - name: Set-up Deployment Version
        run: |
          source gradle.properties
          echo ${version}
          sed -ie "s/{{VERSION}}/$version/g" ./deploy/deployment.yaml

      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy All
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 pokebattle-staging-cluster
          kubectl apply -f ./deploy/configmap.yml
          kubectl apply -f ./deploy/ingress.yml
          kubectl apply -f ./deploy/mysql-deploy.yml
          kubectl apply -f ./deploy/deployment.yaml