name: Linter
on:
  push:
    branches:
      - master
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login into Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Java Image
        env:
          docker_user: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_pass: ${{ secrets.DOCKERHUB_TOKEN }}
        run: ./gradlew build jib -x test

      - name: Get Image Version
        run: source gradle.properties

      - name: Print Version
        run: echo $version

      - name: Change Deploy YML
        run: sed -ie "s/{{VERSION}}/$version/g" ./deploy/deployment.yaml
