name: Linter
on:
  push:
    branches:
      - master
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
#generate image
      - name: Login into Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
      - name: Generate Tag
        id: generate_tag
        uses: Surgo/docker-smart-tag-action@v1
        with:
          docker_image: ${{ github.event.repository.name }}
          default_branch: ${{ github.event.repository.default_branch }}
          tag_with_sha: true

      - name: Push Image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.generate_tag.outputs.tag }}

